### ISSUE TITLE
Not a issue more of a complaint

### ISSUE THREAD

**Issue by OfficiallyYanKelly** [AngeloCore/discord-buttons#46]
They are not willing to help new people who dont know how to code, they say, go learn javascript, and not to be rude, thats not fucking nice, but meh

**Comment by EhsanFox** [comment]
we expect who uses our module knows the basic of javascript, Supports/Contributors are not javascript teachers, they help you with any errors that came from the module!
nothing more!

**Comment by Galaxy-Coding** [comment]
@OfficiallyYanKelly I saw you on discord and it’s not really rude, but we are volunteering to help you and we have zero obligation to help anyone. I am spending my free time helping other people and I won’t help people that don’t know Javascript because they don’t know the fundamentals. It’s like teaching students algebra but they don’t know addition. If you want some resources to learn JavaScript, go to https://javascript.info/ They have an awesome tutorial and I hope you will like it.

**Comment by OfficiallyYanKelly** [comment]
> @OfficiallyYanKelly I saw you on discord and it’s not really rude, but we are volunteering to help you and we have zero obligation to help anyone. I am spending my free time helping other people and I won’t help people that don’t know Javascript because they don’t know the fundamentals. It’s like teaching students algebra but they don’t know addition. If you want some resources to learn JavaScript, go to https://javascript.info/ They have an awesome tutorial and I hope you will like it.

I understand that But I have also seen people asking for help and just been shouted at no, I am fully able to code myself, I know what im doing but Just feel like we all could help people who are just starting toc ode

**Comment by Galaxy-Coding** [comment]
@OfficiallyYanKelly 
I’m sorry if you felt like someone shouted at you. Of course I have respect to people who are new to the JavaScript community. Unfortunately, It’s very difficult to help people resolve errors that they would have solved if they had a little more JavaScript knowledge. This doesn’t mean I don’t want anyone to feel unwelcome. The problem is that if someone doesn’t have enough knowledge on something specific, It’s a bad idea to straight up give someone the answer without (whoever needs help) full understanding the code. You won’t learn anything that way. My idea is that I will help (whoever needs help) as much as I can and if necessary link them to a tutorial/video that throughly explains the topic.

**Comment by EhsanFox** [comment]
if anyone asks for any help about a problem/error that comes from our package, we would answer and help them with respect,
But when someone asks about his own error(a basic javascript error) we are not gonna help them and we would just tell them to Learn javascript before making a bot!

**Comment by AngeloCore** [comment]
I will personally check
