### ISSUE TITLE
TypeError: Cannot read property 'MessageButton' of undefined

### ISSUE THREAD

**Issue by LeviOP** [AngeloCore/discord-buttons#62]
When using the code in a desktop environment it works fine but when I ran the code on repl.it it just stopped working and returned this error. If I console.log the `require('discord-buttons')` by itself it returns the function just fine, but when I console.log `disbut` after the `const disbut = require('discord-buttons')(client);` line, it returns `undefined`. Any help is appreciated! Thanks!

**Comment by eslym** [comment]
I will call this as a wrong documentation rather than a bug

```js
const dc = require('discord.js');
const bot = new dc.Client();
const btn = require('discord-buttons');

btn(bot);

let button = new btn.MessageButton();
```

**Comment by LeviOP** [comment]
This doesn't change anything. Your code accomplishes the exact same thing as
```js
const discord = require('discord.js'); //Define the discord.js module
const client = new discord.Client(); //Creating discord.js client (constructor)
const disbut = require('discord-buttons')(client)
```

**Comment by eslym** [comment]
that probably caused by different version tho, if you read the latest https://github.com/AngeloCore/discord-buttons/blob/fddc6e5a79f4e6cd833add5c7dd328f230f23c32/src/index.js#L44 then you will realize it returns nothing while the version 2.4.1 https://github.com/AngeloCore/discord-buttons/blob/560d0e51813a13d18e7dcb122d988e94e23fd38f/src/index.js#L29 did return a MessageButton in the function

**Comment by LeviOP** [comment]
So you're suggesting that I use an older version of the package to make it work?

**Comment by es183923** [comment]
I'm currently using 
```js
const discord = require('discord.js');
const client = new discord.Client();
require('discord-buttons')(client);
const disbut = require('discord-buttons');
```
and it's working fine.
